<div class="col-md-6 col-xs-12">

	<div class="col-md-3 col-xs-12">
		 <img src="<?php echo $block->getLayout()->getBlock('logo')->getLogoSrc(); ?>"
		      alt="<?php echo $block->getLayout()->getBlock('logo')->getLogoAlt(); ?>"
		  />
	</div>	  
	<div class="col-md-9 col-xs-12">  
		  <p style="margin-top: 20px;">It's Not You... It's Your Clubs.</p>   
	</div>
	
</div>	


<div class="col-md-6 col-xs-12">
	<p class="copyrights">(c) Copyright 2018 2ndswing.com</p>
</div>	