<div class="help-box block">
	<div class="title">Need Help?</div>
	<div class="content">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('checkout_help_content')->toHtml();?>
	</div>
</div>	

<div class="email-box block">
<div class="title">Email Customer Service</div>
	<div class="content">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('checkout_email_content')->toHtml();?>
	</div>
</div>		